import Head from "next/head";
import Homepage from "../src/Screens/Homepage";
import styles from "../styles/Home.module.css";
import AboutPage from "../src/Screens/AboutPage";
import ContactUs from "../src/components/ContactUs";
import Products from "../src/Screens/ProductsPage/Products";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pt. Babu lal sharma perfume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
      <Products />
      <AboutPage />
      <ContactUs />
    </div>
  );
}
